BASE_PATH = "/home/ubuntu/SlurmDeployment"
TERRAFORM_WORKING_DIRECTORY = f"{BASE_PATH}/TerraformSlurmCluster"

ANSIBLE_WORKING_DIRECTORY = f"{BASE_PATH}/AnsibleSlurmCluster"
ANSIBLE_LOGS_DIRECTORY = f"{BASE_PATH}/ansible_logs"
PLAYBOOKS_DIRECTORY = f"{ANSIBLE_WORKING_DIRECTORY}/playbooks"
INVENTORY_PATH = f"{ANSIBLE_WORKING_DIRECTORY}/inventory"
